stages:
  data_ingestion:
    cmd: python src/CNNclassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/CNNclassifier/pipeline/stage_01_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts_root/data_ingestion/kidney-ct-scan-image

  prepare_base_model:
    cmd: python src/CNNclassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/CNNclassifier/pipeline/stage_02_prepare_base_model.py
      - configs/config.yaml
    
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts_root/prepare_base_model

  training:
    cmd: python src/CNNclassifier/pipeline/stage_03_model_training.py
    deps:
      - src/CNNclassifier/pipeline/stage_03_model_training.py
      - configs/config.yaml
      - artifacts_root/data_ingestion/kidney-ct-scan-image
      - artifacts_root/prepare_base_model

    params:
      - EPOCHS
      - BATCH_SIZE
      - IMAGE_SIZE
      - AUGMENTATION
    outs:
      - artifacts_root/training/model.h5

  evaluation:
    cmd: python src/CNNclassifier/pipeline/stage_04_model_evaluation_with_mlflow.py
    deps:
      - src/CNNclassifier/pipeline/stage_04_model_evaluation_with_mlflow.py
      - configs/config.yaml
      - artifacts_root/data_ingestion/kidney-ct-scan-image
      - artifacts_root/prepare_base_model
      - artifacts_root/training/model.h5

    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
      - scores.json:
          cache: False