artifacts_root: artifacts_root

data_ingestion:
  root_dir: artifacts_root/data_ingestion
  source_URL: https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing
  local_data_file: artifacts_root/data_ingestion/data.zip
  unzip_dir: artifacts_root/data_ingestion

 
prepare_base_model:
  root_dir: artifacts_root/prepare_base_model
  base_model_path: artifacts_root/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts_root/prepare_base_model/base_model_updated.h5


training:
  root_dir: artifacts_root/training
  trained_model_path: artifacts_root/training/model.h5


mlflow_config:
  tracking_uri: "https://dagshub.com/darkathon89/Kidney-Disease.mlflow"
  username: "darkathon89"
  password: "9c6a621ab46434d5e99ba9b0be13ae5e31c233dd"